application:
  debug: true
kafka:
  src:
    bootstrap:
      servers1: 169.254.9.188:9092
      servers: kafka-0.mh-nfaesozrbxarqnjfnzecnsr.eu-de.containers.appdomain.cloud:9093
    username1: mmo275
    password1: Passw0rd
    username: token
    password: D3CKp9bhZj58V0e3lTMBi1Y5zySNYGsb1_ReUabCMov0    
    topic: mmo275topic
    security1:
      protocol1: SASL_PLAINTEXT
    sasl1:
      mechanism1: SCRAM-SHA-256
    clientId: kafka-to-mq
    login:
      module: org.apache.kafka.common.security.scram.ScramLoginModule
    truststore-location: C:\Program Files\Java\jdk-10.0.1\lib\security\cacerts
    truststore-password: changeit
  debug: true
ibm:
  mq:
    queueManager: QMAP01
    channel: MQ.MONITOR.SVRCONN
    connName: localhost(1442)
    sslCipherSpec: TLS_RSA_WITH_AES_256_CBC_SHA256
    useSSL: false
    user: 
    password: 
    queue: KAFKA.IN
    mqmd:
      rfh2: 
        include: false
      expiry: 600
      messageType:
# reqType ; 1 = REQUEST, 8 = DATAGRAM
        reqType: 1
        replyToQM: 
        replyToQueue: MICK.OUT
    security:
      truststore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01jks.jks
      truststore-password: Passw0rd
      keystore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01jks.jks
      keystore-password: Passw0rd  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
server:
  port:
    8082
